config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #List all the tasks
  get 'tasks', to: 'tasks#index'

  #New task
  get 'tasks/new', to: 'tasks#new'

  #Read one
  get 'tasks/:id', to: 'tasks#show', as: :task

  #Create the new task
  post 'tasks', to: 'tasks#create'

  #Edit a task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit

  #Update a task
  patch 'tasks/:id', to: 'tasks#update'

  #Delete
  delete 'tasks/:id', to: 'tasks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(params[:id])
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css" integrity="sha256-PF6MatZtiJ8/c9O9HQ8uSUXr++R9KBYu4gbNG5511WE=" crossorigin="anonymous" />

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for (task) do |t| %>
<div class="form-group">
  <%= t.label :title %>
  <%= t.text_field :title, class: 'form-control' %>
</div>
<div class="form-group">
  <%= t.label :details %>
  <%= t.text_field :details, class: 'form-control' %>
</div>
<div class="form-group">
<% unless t.object.new_record? %>
<%= t.label :completed %>
<%= t.check_box :completed %>
<% end %>
</div>
<%= t.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul>
<% @tasks.each do |task| %>
<li>
  <% if task.completed == true %>
  <i class="far fa-check-square"></i>
  <% else %>
  <i class="far fa-square"></i>
  <% end %>
  <%= link_to task.title, task_path(task) %>
  <%= link_to task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } do %>
      <i class="fas fa-trash-alt"></i>
      <% end %>
<% end %>
</li>
</ul>
<hr>
<%= link_to 'Add a new task', tasks_new_path %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task%>

app/views/tasks/show.html.erb
<div class="title">
<h1><%= @task.title %></h1>
<%= link_to 'Edit the task', task_edit_path(@task) %>
</div>

<div class="detail"> <%= @task.details %> </div>

<% if @task.completed == true %>
<p> <i class="far fa-check-square"></i> This task is completed </p>
<% else %>
<p> <i class="far fa-square"></i> This task is not completed yet</p>
<% end %>

<%= link_to 'Back to list', tasks_path %>